config/routes.rb
Rails.application.routes.draw do
  
  resources :items
  resources :employs
   devise_for :users    #, path_names: { 
    #sign_up: '' #Stop Sign Up
  #}
  root to: 'holders#index'
  resources :holders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employ.rb
class Employ < ApplicationRecord
end

app/models/holder.rb
class Holder < ApplicationRecord
	validates :tazkira_number, confirmation: true
	validates :tazkira_number,   :presence => {:message => 'tazkira_number must entered'},
                     :numericality => true,
                     :length => { :minimum => 6, :maximum => 12}        
 validates :mobile_number,   :presence => {:message => 'mobile_number must entered'},
                     :numericality => true,
                     :length => { :minimum => 11, :maximum => 13} 
 validates :tazkira_number, uniqueness: true 
                     
	
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/employs_controller.rb
class EmploysController < ApplicationController
  before_action :set_employ, only: [:show, :edit, :update, :destroy]

  # GET /employs
  # GET /employs.json
  def index
    @employs = Employ.all
  end

  # GET /employs/1
  # GET /employs/1.json
  def show
  end

  # GET /employs/new
  def new
    @employ = Employ.new
  end

  # GET /employs/1/edit
  def edit
  end

  # POST /employs
  # POST /employs.json
  def create
    @employ = Employ.new(employ_params)

    respond_to do |format|
      if @employ.save
        format.html { redirect_to @employ, notice: 'Employ was successfully created.' }
        format.json { render :show, status: :created, location: @employ }
      else
        format.html { render :new }
        format.json { render json: @employ.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employs/1
  # PATCH/PUT /employs/1.json
  def update
    respond_to do |format|
      if @employ.update(employ_params)
        format.html { redirect_to @employ, notice: 'Employ was successfully updated.' }
        format.json { render :show, status: :ok, location: @employ }
      else
        format.html { render :edit }
        format.json { render json: @employ.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employs/1
  # DELETE /employs/1.json
  def destroy
    @employ.destroy
    respond_to do |format|
      format.html { redirect_to employs_url, notice: 'Employ was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employ
      @employ = Employ.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employ_params
      params.require(:employ).permit(:emp_name, :emp_father_name, :sallary, :designation, :starting_date, :mobile_number)
    end
end

app/controllers/holders_controller.rb
class HoldersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_holder, only: [:show, :edit, :update, :destroy]

  # GET /holders
  # GET /holders.json
  def index
    @holders = Holder.all
  end

  # GET /holders/1
  # GET /holders/1.json
  def show
  end

  # GET /holders/new
  def new
    @holder = Holder.new
  end

  # GET /holders/1/edit
  def edit
  end

  # POST /holders
  # POST /holders.json
  def create
    @holder = Holder.new(holder_params)

    respond_to do |format|
      if @holder.save
        format.html { redirect_to @holder, notice: 'Holder was successfully created.' }
        format.json { render :show, status: :created, location: @holder }
      else
        format.html { render :new }
        format.json { render json: @holder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holders/1
  # PATCH/PUT /holders/1.json
  def update
    respond_to do |format|
      if @holder.update(holder_params)
        format.html { redirect_to @holder, notice: 'Holder was successfully updated.' }
        format.json { render :show, status: :ok, location: @holder }
      else
        format.html { render :edit }
        format.json { render json: @holder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holders/1
  # DELETE /holders/1.json
  def destroy
    @holder.destroy
    respond_to do |format|
      format.html { redirect_to holders_url, notice: 'Holder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holder
      @holder = Holder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holder_params
      params.require(:holder).permit(:f, :father_nam, :tazkira_number, :mobile_number, :sex, :address)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:itm_name, :price, :brought_by, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employs_helper.rb
module EmploysHelper
end

app/helpers/holders_helper.rb
module HoldersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/employs/_form.html.erb
<% content_for :title, "Add Staff" %>

<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Add Staff <small>Please </small></h5>
    <div class="ibox-tools">
      <a class="collapse-link">
        <i class="fa fa-chevron-up"></i>
      </a>
      <a class="close-link">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="row">


<%= simple_form_for(@employ) do |f| %>
  <%= f.error_notification %>
<div class="col-sm-6 b-r"><h3 class="m-t-none m-b">Staff Info</h3>
         
    
              <div class="form-group">
              <label>Staff Name</label>
              <%= f.text_field :emp_name, :placeholder=>"Enter staff name", :class=>"form-control", :required=>'' %>
            </div>
        
            <div class="form-group">
              <label>Father Name</label>
              <%= f.text_field :emp_father_name, :placeholder=>"Enter father name", :class=>"form-control", :required=>'' %>
            </div>
            <div class="form-group">
              <label>Sallary</label>
              <%= f.text_field :sallary, :placeholder=>"Enter sallary", :class=>"form-control", :required=>'' %>
            </div>


            <div class="form-group">
              <label>Father Name</label>
              <%= f.text_field :designation, :placeholder=>"Enter designation", :class=>"form-control", :required=>'' %>
            </div>
            
            <div class="form-group">
              <label>Starting Date</label>
              <%= f.date_field :starting_date %>
            </div>
             </div>

             <div class="form-group">
              <label>Mobile Number</label>
              <%= f.text_field :mobile_number, :placeholder=>"Enter Mobile Number", :class=>"form-control", :required=>'' %>
            </div>
             
  <div class="col-sm-12">
            <div class="hr-line-dashed"></div>
            <%= f.submit :class=>"btn btn-sm btn-primary pull-right m-t-n-xs" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/employs/edit.html.erb
<h1>Editing Employ</h1>

<%= render 'form', employ: @employ %>

<%= link_to 'Show', @employ %> |
<%= link_to 'Back', employs_path %>

app/views/employs/index.html.erb
<% content_for :title, "All Staff" %>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>All Staff</h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <a class="close-link">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="ibox-content">

        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
              <tr>
                <th>Staff Name</th>
                <th>Father Name</th>
                <th>Sallary</th>
                <th>Designation</th>
                <th>Starting date</th>
                <th>Mobile number</th>
                <th>***</th>
                            <th>Buttons</th>
                        </tr>
            </thead>

            <tbody>

            <% @employs.each do |employ| %>
              <tr>    
        <<td><%= employ.emp_name %></td>
        <td><%= employ.emp_father_name %></td>
        <td><%= employ.sallary %></td>
        <td><%= employ.designation %></td>
        <td><%= employ.starting_date %></td>
        <td><%= employ.mobile_number %></td>
         <td><span class="badge badge-primary"> </span></td>
                <td>
                  <%= link_to employ_path(employ.id), :class=>'btn btn-white btn-bitbucket', method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to edit_employ_path(employ.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to employ_path(employ.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-print" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>

            </tbody>

            <tfoot>
              <tr>
              <th>Staff Name</th>
                <th>Father Name</th>
                <th>Sallary</th>
                <th>Designation</th>
                <th>Starting date</th>
                <th>Mobile number</th>
                <th>***</th>
                            <th>Buttons</th>
              </tr>
            </tfoot>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>





<%= link_to 'NEW Entry', new_employ_path(@employ) %> |

app/views/employs/new.html.erb
<h1>New Employ</h1>

<%= render 'form', employ: @employ %>

<%= link_to 'Back', employs_path %>

app/views/employs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp name:</strong>
  <%= @employ.emp_name %>
</p>

<p>
  <strong>Emp father name:</strong>
  <%= @employ.emp_father_name %>
</p>

<p>
  <strong>Sallary:</strong>
  <%= @employ.sallary %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @employ.designation %>
</p>

<p>
  <strong>Starting date:</strong>
  <%= @employ.starting_date %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @employ.mobile_number %>
</p>

<%= link_to 'Edit', edit_employ_path(@employ) %> |
<%= link_to 'Back', employs_path %>

app/views/holders/edit.html.erb
<h1>Editing Holder</h1>

<%= render 'form', holder: @holder %>

<%= link_to 'Show', @holder %> |
<%= link_to 'Back', holders_path %>

app/views/holders/index.html.erb
<% content_for :title, "All Voters" %>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>All Voters info</h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <a class="close-link">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="ibox-content">

        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
              <tr>
                <th>Name</th>
      <th>Father name</th>
      <th>Sticker number</th>
      <th>Mobile number</th>
      <th>Sex</th>
      <th>Polling Station Address</th>
                <th>***</th>
                            <th>Buttons</th>
                        </tr>
            </thead>

            <tbody>

            <% @holders.each do |holder| %>
      <tr>
        <td><%= holder.f %></td>
        <td><%= holder.father_nam %></td>
        <td><%= holder.tazkira_number %></td>
        <td><%= holder.mobile_number %></td>
        <td><%= holder.sex %></td>
        <td><%= holder.address %></td>
         <td><span class="badge badge-primary"> </span></td>
                <td>
                  <%= link_to holder_path(holder.id), :class=>'btn btn-white btn-bitbucket', method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to edit_holder_path(holder.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to holder_path(holder.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-print" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>

            </tbody>

            <tfoot>
              <tr>
              <th>Name</th>
      <th>Father name</th>
      <th>Sticker number</th>
      <th>Mobile number</th>
      <th>Sex</th>
      <th>Polling Station Address</th>
                <th>***</th>
                            <th>Buttons</th>
              </tr>
            </tfoot>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>

<%= link_to 'NEW Entry', new_holder_path(@holder) %> |

app/views/holders/new.html.erb
<h1>New Holder</h1>

<%= render 'form', holder: @holder %>

<%= link_to 'Back', holders_path %>

app/views/holders/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @holder.f %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @holder.father_nam %>
</p>

<p>
  <strong>sticker number:</strong>
  <%= @holder.tazkira_number %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @holder.mobile_number %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @holder.sex %>
</p>

<p>
  <strong>Polling Station Address:</strong>
  <%= @holder.address %>
</p>
<%= link_to 'NEW Entry', new_holder_path(@holder) %> | 
<%= link_to 'Edit', edit_holder_path(@holder) %> |
<%= link_to 'Back', holders_path %>

app/views/items/_form.html.erb
<% content_for :title, "Add Item" %>

<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Add Product <small>Please </small></h5>
    <div class="ibox-tools">
      <a class="collapse-link">
        <i class="fa fa-chevron-up"></i>
      </a>
      <a class="close-link">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="row">


<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
<div class="col-sm-6 b-r"><h3 class="m-t-none m-b">Item Info</h3>
         
    
              <div class="form-group">
              <label>Product Name</label>
              <%= f.text_field :itm_name, :placeholder=>"Enter Item name", :class=>"form-control", :required=>'' %>
            </div>
        
            <div class="form-group">
              <label>Price</label>
              <%= f.text_field :price, :placeholder=>"Enter item price", :class=>"form-control", :required=>'' %>
            </div>
            <div class="form-group">
              <label>Brought By</label>
              <%= f.text_field :brought_by, :placeholder=>"Enter name who brought", :class=>"form-control", :required=>'' %>
            </div>
            <div class="form-group">
              <label>Date</label>
              <%= f.date_field :date %>
            </div>
             </div>
             
  <div class="col-sm-12">
            <div class="hr-line-dashed"></div>
            <%= f.submit :class=>"btn btn-sm btn-primary pull-right m-t-n-xs" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% content_for :title, "All item" %>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>All Product</h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <a class="close-link">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="ibox-content">

        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
              <tr>
                <th>Product Name</th>
                <th>Price</th>
                <th>Brought By</th>
                <th>Date</th>
                <th>***</th>
                            <th>Buttons</th>
                        </tr>
            </thead>

            <tbody>

            <% @items.each do |item| %>
              <tr>    
        <td><%= link_to item.itm_name, item_path(item)  %></td>
        <td><%= item.price %></td>
        <td><%= item.brought_by %></td>
        <td><%= item.date %></td>
         <td><span class="badge badge-primary"> </span></td>
                <td>
                  <%= link_to item_path(item.id), :class=>'btn btn-white btn-bitbucket', method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to edit_item_path(item.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to item_path(item.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-print" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>

            </tbody>

            <tfoot>
              <tr>
              
                        <th>Product Name</th>
                <th>Price</th>
                <th>Brought By</th>
                <th>Date</th>
                <th>***</th>
                          <th>Buttons</th>
              </tr>
            </tfoot>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>




<%= link_to 'NEW Entry', new_item_path(@item) %> |

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @item.itm_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Brought by:</strong>
  <%= @item.brought_by %>
</p>

<p>
  <strong>Date:</strong>
  <%= @item.date %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<% if user_signed_in? %>

<!DOCTYPE html>
  <html>

    <head>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
      <title><%= yield(:title) %> | د ټولټاکنو شمیره 1397 پاڼه</title>
      <%= csrf_meta_tags %>

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
      <%= stylesheet_link_tag    'application', :media => "all" %>
      <%= stylesheet_link_tag    'print', :media => "print" %>

    </head>

    <body class="fixed-nav fixed-nav-basic"> <!-- min sidemenu: mini-navbar-->
    <div id="wrapper">
      <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
          <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
              <div class="dropdown profile-element">
                <span>
                  <h2 style="font-size: 30px; margin-bottom: 20px; color: #f70b0b">د ټولټاکنو  <span style="color: #1ab394; font-weight: 900">شمیره 1397 پاڼه</span></h2>
                </span>
               
              </div>
              <div class="logo-element">
                <h2 style="font-size: 10px; margin-top: 0px; margin-bottom: 0px; color: #f70b0b">د ټولټاکنو<span style="color: #1ab394; font-weight: 900">شمیره 1397 پاڼه</span></h2>
              </div>
            </li>
            <li class="landing_link">
              <%= link_to items_path do %>
                <i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span> <span class="label label-warning pull-right">HOME</span></a>
              <% end %>
            </li>
            <li class="active">
              <a href="index.html"><i class="fa fa-shopping-bag"></i> <span class="nav-label">محصول</span> <span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><%= link_to "ټول محصول", items_path %></li>
                <li class=""><%= link_to "محصول زیات کړئ", new_item_path %></li>
              </ul>
            </li>
            <li class="active">
              <a href="index.html"><i class="fa fa-shopping-bag"></i> <span class="nav-label">رای ورکوونکي</span> <span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><%= link_to "ټول رایه ورکوونکي", holders_path %></li>
                <li class=""><%= link_to "رای ورکوونکي اضافه کړئ", new_holder_path %></li>
              </ul>
            </li>
            <li class="active">
              <a href="index.html"><i class="fa fa-shopping-bag"></i> <span class="nav-label">کارکوونکي</span> <span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><%= link_to "ټول کارکوونکي", employs_path %></li>
                <li class=""><%= link_to "کارکونکي اضافه کړئ", new_employ_path %></li>
              </ul>
            </li>
            
            
            
            <li>
              <a href="#"><i class="fa fa-cog fa-spin"></i> <span class="nav-label">Profile</span><span class="fa arrow"></span></a>
              <ul class="nav nav-second-level collapse">
                <li><%= link_to "Change Password", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>

      <div id="page-wrapper" class="gray-bg" style="min-height: 600px;">
        <div class="row border-bottom">
          <nav class="navbar navbar-fixed-top white-bg" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
              <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
            
              <li style="padding: 20px 10px">
                <span class="m-r-sm text-muted"><strong>د ټولټاکنو شمیره 1397 پاڼه</strong> Application.</span>
              </li>
              <li class="pull-right">
                <%= link_to destroy_user_session_path, :method => 'delete' do %>
                    <i class="fa fa-sign-out"></i> Log out
                <% end %>
              </li>
            </ul>
          </nav>
        </div>

        <div class="wrapper wrapper-content">

          <% if notice %>
              <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Notice!</strong> <%= notice %>
              </div>
          <% end %>

          <% if alert %>
              <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Alert!</strong> <%= alert %>
              </div>
          <% end %>

          
        <%= yield %>
  
        </div>

        <div class="footer">
          <div class="pull-right">
            BY <strong><span style="color: green">حبیب</span><span style="color:red"> & ځدران</span></strong>
          </div>
          <div>
            <strong>Copyright</strong> حبیب ځدران &copy; <%= Time.now.year %>
          </div>
        </div>
      </div>
    </div></body></html>

    
    <!-- Mainly scripts -->
    <%= javascript_include_tag 'application' %>

    <!-- Custom and plugin javascript -->
    <script type="text/javascript">
      $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
      });
    </script>

    <% if notice %>
      <script>
        $(document).ready(function() {
          setTimeout(function() {
            toastr.options = {
              closeButton: true,
              progressBar: true,
              showMethod: 'slideDown',
              timeOut: 4000
            };
            toastr.success('<%= notice %>', 'Notice');
          }, 1300);
        });
      </script>
    <% end %>

    <script>
      $(document).ready(function(){
        $('.dataTables-example').DataTable({
          dom: '<"html5buttons"B>lTfgitp',
          buttons: [
            { extend: 'copy'},
            {extend: 'csv'},
            {extend: 'excel', title: 'ExampleFile'},
            {extend: 'pdf', title: 'ExampleFile'},

            {extend: 'print',
              customize: function (win){
                $(win.document.body).addClass('white-bg');
                $(win.document.body).css('font-size', '10px');

                $(win.document.body).find('table')
                    .addClass('compact')
                    .css('font-size', 'inherit');
              }
            }
          ]

        });
      });
    </script></body></html>


    </body>
  </html>


<% else %>

<!DOCTYPE html>
  <html>

    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <title>Login | د ټولټاکنو شمیره 1397 پاڼه</title>
      <%= csrf_meta_tags %>

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
      <%= stylesheet_link_tag    'application' %>
    </head>

    <body class="gray-bg">
    <div class="middle-box text-center loginscreen animated fadeInDown">
      <div>
      
        <%= yield %>
        
      </div>
    </div>

    <div class="footer">
      <div class="pull-right">
        BY <strong><span style="color: green">حبیب  &</span><span style="color:red"> ځدران</span></strong>
      </div>
      <div>
        <strong>Copyright</strong> حبیب ځدران &copy; <%= Time.now.year %>
      </div>
    </div>

    <!-- Mainly scripts -->
    <%= javascript_include_tag 'application' %>

    </body>

  </html>

<% end %>